#############################################################################
##
#W  grpint.gi                  Polycyc                           Bettina Eick
##

# Based on ReduceExpoPara, but with IsOne instead of IsBool, and adapted to
# the NormalIntersection algorithm
BindGlobal( "ReduceExpoParaInt", function( ind, indd, gen, rel )
    local n, changed, i, j, c, g, a, b, q;

    n := Length(rel);
    changed := [];
    for i in [1..Length(ind)] do
        if i <= n then
            c := i;
            g := ind[i];
        else
            c := i-n;
            g := indd[i];
        fi;
        if not IsOne(g) and rel[c] = 0 then
            b := LeadingExponent(g);
            for j in [1..i-1] do
                if not IsOne(ind[j]) or not IsOne(indd[j]) then
                    if i <= n then
                        a := Exponents(ind[j])[c];
                    else
                        a := Exponents(indd[j])[c];
                    fi;
                    q := QuoInt(a,b);
                    if q <> 0 then
                        ind[j] := ind[j]*ind[i]^-q;
                        indd[j] := indd[j]*indd[i]^-q;
                        AddSet(changed, j);
                    fi;
                fi;
            od;
            for j in [1..Length(gen)] do
                if i <= n then
                    a := Exponents(gen[j][1])[c];
                else
                    a := Exponents(gen[j][2])[c];
                fi;
                q := QuoInt(a,b);
                if q <> 0 then
                    gen[j][1] := gen[j][1]*ind[i]^-q;
                    gen[j][2] := gen[j][2]*indd[i]^-q;
                fi;
            od;
        fi;
    od;
    return changed;
end );

#############################################################################
##
#F NormalIntersection( N, U ) . . . . . . . . . . . . . . . . . . .  U \cap N
##
## The core idea here is that the intersection U \cap N equals the kernel of
## the natural homomorphism \phi : U \to UN/N ; see also section 8.8.1 of
## the "Handbook of computational group theory".
## So we can apply the methods for computing kernels of homomorphisms, but we
## need the group UN for this as well, at least implicitly.
##
## The resulting algorithm is quite similar to the Zassenhaus algorithm for
## simultaneously computing the intersection and sum of two vector spaces.
InstallMethod( NormalIntersection, "for pcp groups",
               IsIdenticalObj, [IsPcpGroup, IsPcpGroup],
function( N, U )
    local G, coll, rels, igs, igsN, igsU, n, s, todo, I, id, ls, rs, g, h, d,
          al, ar, e, tm, pairs, changed, j, lo, hi, value, depth, c;

	# get common overgroup of N and U
    coll := Collector( N );
    rels := RelativeOrders( coll );
	G    := PcpGroupByCollector( coll );

    igs  := Igs( G );
    igsN := Cgs( N );
    igsU := Cgs( U );
    n    := Length( igs );

    # if N or U is trivial
    if Length( igsN ) = 0 then
        return N;
    elif Length( igsU ) = 0 then
        return U;
    fi;

    # if N or U are equal to G
    if Length(igsN) = n and ForAll(igsN, x -> LeadingExponent(x) = 1) then
        return U;
    elif Length(igsU) = n and ForAll(igsU, x -> LeadingExponent(x) = 1) then
        return N;
    fi;

    # if N is a tail, we can read off the result directly
    s := Depth( igsN[1] );
    if Length( igsN ) = n-s+1 and
       ForAll( igsN, x -> LeadingExponent(x) = 1 ) then
        I := Filtered( igsU, x -> Depth(x) >= s );
        return SubgroupByIgs( G, I );
    fi;

    # if U is contained in N or vice versa
    if ForAll(igsU, g -> g in N) then
        return U;
    elif ForAll(igsN, g -> g in U) then
        return N;
    fi;

    # Igs of subgroup generated by (u,u)'s and (n,1)'s in G x G
    # rows (1,u) then give the intersection N ∩ U
    id := One(G);
    ls := ListWithIdenticalEntries(2*n, id);
    rs := ListWithIdenticalEntries(2*n, id);
    c  := 2*n+1;

    for g in igsU do
        d := Depth( g );
        ls[d] := g;
        rs[d] := g;
    od;

    # insert N
    todo := List(igsN, g -> [g, id]);

    # depth in G x G
    depth := function(pair)
        if pair[1] <> id then return Depth(pair[1]); fi;
        return n + Depth(pair[2]);
    end;

    # optimisation similar to AddToIgs
    value := function(pair)
        if pair[1] <> id then
            return [2*n-Depth(pair[1]), AbsInt(LeadingExponent(pair[1]))];
        elif pair[2] <> id then
            return [n-Depth(pair[2]), AbsInt(LeadingExponent(pair[2]))];
        else
            return [-1, 0];
        fi;
    end;

    # enter the pairs of todo
    while not IsEmpty(todo) and c > 1 do
        tm := Remove(todo, PositionMinimum(List(todo, value)));
        al := tm[1];
        ar := tm[2];
        changed := [];

        while al <> id or ar <> id do
            if al <> id then
                d  := Depth( al );
                g := al;
                h := ls[d];
            else
                d := n + Depth(ar);
                g := ar;
                h := rs[d];
            fi;
            if d >= c then break; fi;

            if h = id then
                e := NormingExponent(g);
                ls[d] := al ^ e;
                rs[d] := ar ^ e;
                AddSet(changed, d);
                if d <= n then
                    h := ls[d];
                else
                    h := rs[d];
                fi;
            fi;

            if al = ls[d] and ar = rs[d] then
                al := id;
                ar := id;
            elif LeadingExponent(g) mod LeadingExponent(h) = 0 then
                e := LeadingExponent(g) / LeadingExponent(h);
                if e = 1 and al = ls[d] then
                    al := id;
                else
                    al := al * ls[d] ^ -e;
                fi;
                if e = 1 and ar = rs[d] then
                    ar := id;
                else
                    ar := ar * rs[d] ^ -e;
                fi;
            elif d <= n then
                pairs := GcdPcpPara( ls[d], al, rs[d], ar );
                ls[d] := pairs[1];
                al := pairs[2];
                rs[d] := pairs[3];
                ar := pairs[4];
                AddSet(changed, d);
            else
                pairs := GcdPcp(rs[d], ar);
                rs[d] := pairs[1];
                ar := pairs[2];
                AddSet(changed, d);
            fi;
        od;

        if IsEmpty(changed) then
            continue;
        fi;
        UniteSet(changed, ReduceExpoParaInt(ls, rs, todo, rels));

        # if tail is complete, remove corresponding things in todo
        while c > 1 do
            if c-1 <= n then
                g := ls[c-1];
            else
                g := rs[c-1];
            fi;
            if g = id or LeadingExponent(g) <> 1 then
                break;
            fi;
            c := c-1;
        od;
        todo := Filtered(todo, pair -> depth(pair) < c);

        # add powers and commutators
        for d in changed do
            if d < c-1 then
                if d <= n then
                    g := ls[d];
                else
                    g := rs[d];
                fi;
                e := RelativeOrderPcp(g);
                if e > 0 then
                    tm := [ls[d] ^ e, rs[d] ^ e];
                    if depth(tm) < c then
                        Add(todo, tm);
                    fi;
                fi;
            fi;
            for j in [1..2*n] do
                if j = d or (j < d and j in changed) or
                   Minimum(d, j) >= c-1 or
                   (ls[j] = id and rs[j] = id) then continue; fi;
                lo := Minimum(d, j);
                hi := Maximum(d, j);
                tm := [Comm(ls[hi], ls[lo]), Comm(rs[hi], rs[lo])];
                if depth(tm) < c then
                    Add(todo, tm);
                fi;
                if lo <= n then
                    g := ls[lo];
                else
                    g := rs[lo];
                fi;
                if RelativeOrderPcp(g) = 0 then
                    tm := [Comm(ls[hi], ls[lo] ^ -1),
                           Comm(rs[hi], rs[lo] ^ -1)];
                    if depth(tm) < c then
                        Add(todo, tm);
                    fi;
                fi;
            od;
        od;
    od;

    I := Filtered(rs{[n+1..2*n]}, x -> x <> id);
    return SubgroupByIgs( G, I );
end );

#############################################################################
##
#M Intersection( N, U )
##
InstallMethod( Intersection2, "for pcp groups",
               IsIdenticalObj, [IsPcpGroup, IsPcpGroup],
function( U, V )
    # check for trivial cases
    if IsInt(Size(U)) and IsInt(Size(V)) then
        if IsInt(Size(V)/Size(U)) and ForAll(Igs(U), x -> x in V ) then
            return U;
        elif Size(V)<Size(U) and IsInt(Size(U)/Size(V))
             and ForAll( Igs(V), x -> x in U ) then
            return V;
        fi;
    fi;

    # test if one the groups is known to be normal
    if IsNormal( V, U ) then
        return NormalIntersection( U, V );
    elif IsNormal( U, V ) then
        return NormalIntersection( V, U );
    fi;

    if IsFinite( U ) or IsFinite( V ) then
        TryNextMethod();
    fi;
    Error("sorry: intersection for non-normal groups not yet installed");
end );
