name: Polycyclic
version: "2.17"
license: "GPL-2.0-or-later"
date: 2025-08-28
description: |
    Computation with polycyclic groups

authors:
    - name: Bettina Eick
      url: http://www.iaa.tu-bs.de/beick
    - name: Werner Nickel
      url: http://www.mathematik.tu-darmstadt.de/~nickel/
    - name: Max Horn
      url: https://www.quendi.de/math

maintainers:
    - name: Bettina Eick
      url: http://www.iaa.tu-bs.de/beick
    - name: Max Horn
      url: https://www.quendi.de/math
    - name: Óscar Fernández Ayala
      url: https://Osferay.github.io
    - name: Sam Tertooy
      url: https://stertooy.github.io/

GAP: ">= 4.10"

needed-pkgs:
    - name: "alnuth"
      version: "3.0"
      url: "https://gap-packages.github.io/alnuth"
    - name: "autpgrp"
      version: "1.6"
      url: "https://gap-packages.github.io/autpgrp/"

www: https://gap-packages.github.io/polycyclic/
readme: README.md
packageinfo: https://gap-packages.github.io/polycyclic/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/polycyclic/releases/download/v2.17/polycyclic-2.17.tar.gz

abstract: |
    This package provides various algorithms for computations with polycyclic groups defined by polycyclic presentations.

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    finitely generated nilpotent groups, metacyclic groups, collection, consistency check, solvable word problem, normalizers, centralizers, intersection, conjugacy problem, subgroups of finite index, torsion subgroup, finite subgroups, extensions, complements, cohomology groups, orbit-stabilizer algorithms, fitting subgroup, center, infinite groups, polycyclic generating sequence, polycyclic presentation, polycyclic group, polycyclically presented group, polycyclic presentation, maximal subgroups, Schur cover, Schur multiplicator.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>ENHAT25</span>]   <b class='BibAuthor'>Eick, B., Nickel, W., Horn, M., Fernández Ayala, Ó. and Tertooy, S.</b>,
     <i class='BibTitle'>Polycyclic, Computation with polycyclic groups,
             Version 2.17</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/polycyclic/">https://gap-packages.github.io/polycyclic/</a></span>.
    </p>
    

bibtex: |
    @misc{ Polycyclic,
      author =           {Eick,   B.   and   Nickel,   W.   and   Horn,  M.  and
                          Fern{\a'a}ndez Ayala, {\a'O}. and Tertooy, S.},
      title =            {{Polycyclic},  {Computation  with  polycyclic groups},
                          {V}ersion 2.17},
      month =            {Aug},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href     {https://gap-packages.github.io/polycyclic/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{polycyclic/}}},
      keywords =         {finitely   generated   nilpotent   groups;  metacyclic
                          groups;  collection;  consistency check; solvable word
                          problem;   normalizers;   centralizers;  intersection;
                          conjugacy  problem; subgroups of finite index; torsion
                          subgroup;  finite  subgroups; extensions; complements;
                          cohomology groups; orbit\texttt{\symbol{45}}stabilizer
                          algorithms; fitting subgroup; center; infinite groups;
                          polycyclic     generating     sequence;     polycyclic
                          presentation;    polycyclic    group;   polycyclically
                          presented   group;  polycyclic  presentation;  maximal
                          subgroups; Schur cover; Schur multiplicator},
      printedkey =       {ENHAT25}
    }

